package main.java.exception;

public enum UtilidadesExceptionEnum {
	
	ERROR_LECTURA, FICHERO_NO_EXISTE, ERROR_INSTANCIACION, ERROR_CONEXION, ERROR_CIERRE_RECURSO,
	ERROR_ESCRITURA, ERROR_CREACION, ERROR_DATOS_CONSULTA, ERROR_EJECUCION_CONSULTA;
}
